server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<path>.*), /${path}

        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/api/quizzes/**
          filters:
            - RewritePath=/api/quizzes/(?<path>.*), /${path}

        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/questions/**
          filters:
            - RewritePath=/api/questions/(?<path>.*), /${path}

        - id: result-service
          uri: lb://result-service
          predicates:
            - Path=/api/results/**
          filters:
            - RewritePath=/api/results/(?<path>.*), /${path}

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
